/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  stringToAnyDict,
  stringToStringDict,
} from './utils/type-aliases';

export namespace Components {
  interface PwcFilter {
    'data': string | stringToAnyDict[];
    'getFilteredData': () => Promise<stringToAnyDict[]>;
    'mapping': string | stringToStringDict[];
  }
}

declare global {


  interface HTMLPwcFilterElement extends Components.PwcFilter, HTMLStencilElement {}
  var HTMLPwcFilterElement: {
    prototype: HTMLPwcFilterElement;
    new (): HTMLPwcFilterElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-filter': HTMLPwcFilterElement;
  }
}

declare namespace LocalJSX {
  interface PwcFilter {
    'data'?: string | stringToAnyDict[];
    'mapping'?: string | stringToStringDict[];
  }

  interface IntrinsicElements {
    'pwc-filter': PwcFilter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-filter': LocalJSX.PwcFilter & JSXBase.HTMLAttributes<HTMLPwcFilterElement>;
    }
  }
}


