/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ItemConfig,
} from './components/pwc-filter/ItemConfig';
import {
  FilterChangedEventPayload,
} from './components/pwc-filter/FilterChangedEventPayload';

export namespace Components {
  interface PwcFilter {
    'data': string | object[];
    'filter': () => Promise<object[]>;
    /**
    * If this is true, the same string representation is assigned to null and undefined values for generated pwc-choices options.
    */
    'handleNullAndUndefinedSeparately': boolean;
    'items': string | ItemConfig[];
  }
}

declare global {


  interface HTMLPwcFilterElement extends Components.PwcFilter, HTMLStencilElement {}
  var HTMLPwcFilterElement: {
    prototype: HTMLPwcFilterElement;
    new (): HTMLPwcFilterElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-filter': HTMLPwcFilterElement;
  }
}

declare namespace LocalJSX {
  interface PwcFilter {
    'data'?: string | object[];
    /**
    * If this is true, the same string representation is assigned to null and undefined values for generated pwc-choices options.
    */
    'handleNullAndUndefinedSeparately'?: boolean;
    'items'?: string | ItemConfig[];
    'onFilterChanged'?: (event: CustomEvent<FilterChangedEventPayload>) => void;
  }

  interface IntrinsicElements {
    'pwc-filter': PwcFilter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-filter': LocalJSX.PwcFilter & JSXBase.HTMLAttributes<HTMLPwcFilterElement>;
    }
  }
}


